steps:
- name: 'gcr.io/$PROJECT_ID/envsubst'
  args: ['deployment.yaml', 'deployment.yaml']
  env: ['COMMIT_SHA=$COMMIT_SHA']
  dir: '/'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/flerpo_diagnoskod:$COMMIT_SHA', '.']
  dir: '/'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flerpo_diagnoskod']
  dir: '/'

images: ['gcr.io/$PROJECT_ID/flerpo_diagnoskod:$COMMIT_SHA']
