steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/flerpo_diagnoskod:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flerpo_diagnoskod']


- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', ' --project', '$project_name']


images: ['gcr.io/$PROJECT_ID/flerpo_diagnoskod:$SHORT_SHA']
