steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/flerpo_diagnoskod:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flerpo_diagnoskod']

images: ['gcr.io/$PROJECT_ID/flerpo_diagnoskod:$SHORT_SHA']
