steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/flerpo_diagnoskod:master', '.']
  dir: '/'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flerpo_diagnoskod']
  dir: '/'

images: ['gcr.io/$PROJECT_ID/flerpo_diagnoskod:master']
